import sqlite3
conn = sqlite3.connect('data/articles.db')
c = conn.cursor()
c.execute('SELECT COUNT(*) FROM articles')
print('articles総数:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM articles WHERE processed = 1')
print('processed済み:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM articles WHERE processed = 0')
print('未処理:', c.fetchone()[0])
c.execute('SELECT COUNT(*) FROM summaries')
print('summaries総数:', c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM summaries WHERE created_at >= datetime('now','localtime','-24 hours')")
print('24時間以内のsummary:', c.fetchone()[0])
conn.close()
