import sqlite3
conn = sqlite3.connect('data/articles.db')
c = conn.cursor()
c.execute("SELECT COUNT(*) FROM summaries")
print('summaries総数:', c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM summaries WHERE created_at >= date('now', 'localtime')")
print('本日生成:', c.fetchone()[0])
c.execute("SELECT COUNT(*) FROM articles WHERE processed = 1")
print('処理済み記事:', c.fetchone()[0])
conn.close()
